{{- if (and .Values.deploy .Values.metrics.enabled) -}}
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: {{ include "anarchy.name" . }}-metrics-credentials
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "anarchy.labels" . | nindent 4 }}
spec:
  forceRegenerate: false
  data:
    metrics_username: {{ .Values.metrics.username }}
  fields:
  - fieldName: metrics_password
    encoding: "hex"
    length: "32"
{{- end }}
